routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes :::: Admin
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => ['auth', 'verified']], function() {
 
	Route::get('/admin/dashboard', [App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('admin.dashboard');

	Route::resource('admin/sections', App\Http\Controllers\Admin\SectionsController::class, ['except' => ['']]);

	Route::resource('admin/section-ordering', App\Http\Controllers\Admin\SectionSortingController::class, ['except' => []]);

	Route::resource('admin/manage-form', App\Http\Controllers\Admin\FormBuilderController::class, ['except' => ['create']]);

	Route::resource('admin/users', App\Http\Controllers\Admin\UsersController::class, ['except' => ['']]);
   Route::resource('admin/change-password', App\Http\Controllers\Admin\ChangePasswordController::class, ['except' => ['show', 'edit', 'destroy','update', 'create']]);
   
   Route::resource('admin/profile-setting', App\Http\Controllers\Admin\ProfileSettingController::class, ['except' => ['show', 'edit', 'destroy','update', 'create']]);

   Route::resource('admin/developer-console', App\Http\Controllers\Admin\ArtisanConsoleController::class, ['except' => []]);

   Route::resource('admin/section-type', App\Http\Controllers\Admin\SraTypeController::class, ['except' => ['show', 'delete']]);

   Route::resource('admin/sra', App\Http\Controllers\Admin\SraController::class, ['except' => []]);
   
   Route::post('admin/change-field-status', [App\Http\Controllers\Admin\AjaxHandlerController::class, 'index']);

   Route::post('admin/change-section-status', [App\Http\Controllers\Admin\AjaxHandlerController::class, 'changeSecionStatus']);

    Route::post('admin/change-sra-status', [App\Http\Controllers\Admin\AjaxHandlerController::class, 'changeSraStatus']);
   
   Route::post('admin/create-form-field', [App\Http\Controllers\Admin\AjaxHandlerController::class, 'createFormField']);

   Route::post('admin/show-form-field', [App\Http\Controllers\Admin\AjaxHandlerController::class, 'showFormField']);

   Route::resource('admin/form-fields', App\Http\Controllers\Admin\FormFieldOrderingController::class, ['except' => ['create', 'index', 'edit', 'update', 'show', 'destroy']]);

   Route::resource('admin/media', App\Http\Controllers\Admin\MediaController::class, ['except' => ['edit', 'update']]);

   Route::resource('admin/location', App\Http\Controllers\Admin\LocationController::class, ['except' => []]);

   Route::resource('admin/group', App\Http\Controllers\Admin\GroupController::class, ['except' => []]);

   Route::resource('admin/provider', App\Http\Controllers\Admin\ProviderController::class, ['except' => []]);

   Route::resource('admin/sra-map', App\Http\Controllers\Admin\SraMappingController::class, ['except' => []]);

   Route::resource('admin/sra-document', App\Http\Controllers\Admin\SraDocumentController::class, ['except' => []]);

   Route::resource('admin/sra-report', App\Http\Controllers\Admin\SraReportController::class, ['except' => []]);


   Route::get('admin/completed-sra', [App\Http\Controllers\Admin\CommonController::class, 'index'])->name('completed.sra');


});


routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

include('admin.php');

app/Models/Sra.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Auth;

class Sra extends Model
{
    use HasFactory, SoftDeletes, Notifiable;

     /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'is_previous',
        'id_previous',
        'group',
        'provider',
        'location',
        'year',
        'deleted_at',
        'created_by',
        'updated_by'
  
    ];

    protected $dates = ['deleted_at'];
    
    
    public static function boot()
    {
        parent::boot();

        static::creating(function($model)
        {
            $user = Auth::user();           
            $model->created_by = $user->id;
            $model->updated_by = $user->id;
        });
        
        static::updating(function($model)
        {
            $user = Auth::user();
            $model->updated_by = $user->id;
        });       
    }

    public function hasLocation() {
       
       return $this->belongsTo('App\Models\Location', 'location', 'id');
 
    }

    public function hasGroup() {

        return $this->belongsTo('App\Models\Group', 'group', 'id')->with('hasProviders');
    }

    public function sraMapped() {

        return $this->hasMany('App\Models\SraMapping', 'sra_id', 'id');
    }


    public function sraDocuments() {

        return $this->hasMany('App\Models\SraDocuments', 'sra_id', 'id');
    }

}

app/Models/SraType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SraType extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'description'
    ];

    public static function sraTypeAttributes() {
        
        $selectSraType    = self::get()->pluck('name', 'id');

        return $selectSraType;
    }
}

app/Http/Controllers/Admin/SraController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\Sra\StoreSraRequest;
use App\Http\Requests\Sra\UpdateSraRequest;
use App\Models\Sra;
use App\Models\Group;
use App\Models\Section;
use App\Models\Provider;
use App\Models\Location;
use App\Models\SraMapping;
use Session;
use DB;
use Auth;

class SraController extends Controller
{   
    private $model;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->model_name = trans('app.model.sra');
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        
        $sra = Sra::with(['hasGroup', 'hasLocation'])->orderBy('id', 'DESC')->get();
        
        return view('admin.module.sra._index', compact('sra'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {   
        if($request->ajax()) {
              
              $provider = Provider::selectAttr($request->group);
              
              $return[] = view('admin.module.sra._ajax-provider')->with(['provider' => $provider])->render();

            return response()->json(['message' => $return ]);
        }

        $groups    = Group::selectAttr();

        $locations = Location::selectAttributes(); 

        return view('admin.module.sra._create', compact('groups', 'locations'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreSraRequest $request)
    {   
        
        if($request->previous_year == 1) {
            
           $sra = Sra::with(['hasGroup', 'hasLocation'])->where('group', $request->group)->where('year', '<' , $request->year)->where('location', $request->location)->whereIn('provider' , [implode(',', $request->provider)] )->get();
           
           if($sra->count() > 0) {

                $groups    = Group::selectAttr();

                $locations = Location::selectAttributes(); 
                
                return view('admin.module.sra._create', compact('sra', 'groups', 'locations'));

           } else {

               return back()->with('error', ' No result found');

           } 

        } else  {
            
            $sra = Sra::create( array_merge($request->all(), ['provider' => implode(',', $request->provider) ] ));

            if( ! $sra)
                return back()->with('error', trans('messages.failed'));

            return back()->with(['success' => trans('messages.created', ['model' => $this->model_name]), 'data'    => $sra ]);
        }
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {   
        
        $sra = Sra::find($id);
   
        if(empty($sra)) {

            return redirect( route('sra.index'));
        }
       
        $sections = Auth::user()->sections;
        
        $assignedSections = explode(',', $sections);

        $sections = Section::with(['formFields' => function ($q){
                        $q->orderBy('ordering', 'ASC')->where('status', 1);
                    }, ])->orderBy('ordering', 'ASC')->get();
        
        $sraMapCount = SraMapping::where('sra_id', $id)->count();

        return view('admin.module.sra._show', compact('sections', 'id', 'assignedSections', 'sraMapCount', 'sra'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Sra $sra)
    {  
        
        $groups    = Group::selectAttr();

        $locations = Location::selectAttributes(); 

        $providers = Provider::where('group', $sra->group)->get()->pluck('name', 'id');

       return view('admin.module.sra._edit', compact('sra', 'groups', 'providers', 'locations'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateSraRequest $request, Sra $sra)
    {
        if( $sra->update( array_merge($request->all(), ['provider' => implode(',', $request->provider) ] ) ) )
            return back()->with('success', trans('messages.updated', ['model' => $this->model_name]));

        return back()->with('error', trans('messages.failed'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/module/sra/_ajax-provider.blade.php

{!! Form::label('provider', 'Provider', ['class' => 'required']) !!} 
 (<small>
     <a target="_blank" href="{{ route('provider.create') }}" class="">
             <i class="fa fa-plus"></i>Add Provider
     </a>
</small>)
{!! Form::select('provider[]', $provider, 
                    null, 
                    ['class' => 'form-control select2','placeholder' => 'Pick a option...', 'multiple' => true]) 
                !!}
@error('provider')
  <span class="invalid-feedback" role="alert">
        <strong>{{ $message }}</strong>
  </span>
@enderror

resources/views/admin/module/sra/_create.blade.php
@extends('admin.layouts.master')

@section('title', 'Create New SRA')

@section('content')

<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">@yield('title')</h3>

        </div>
  
        {!! Form::open(['route' => 'sra.store', 'files' => true]) !!}
        
        <div class="card-body">
         
         <div class="form-group"> 

           {!! Form::label('previous sra', 'Generate from previous year', ['class' => 'required']) !!} 

           {!! Form::radio('previous_year', '1', '') !!}
           {!! Form::label('yes', 'Yes') !!}

           {!! Form::radio('previous_year', '0', 1) !!}
           {!! Form::label('no', 'No') !!}

         </div>

         <div class="form-group">
              {!! Form::label('group', 'Group', ['class' => 'required']) !!}
              (<small>
                <a target="_blank" href="{{ route('group.create') }}" class="">
                  <i class="fa fa-plus"></i>Add Group
                </a>
              </small>)
              {!! Form::select('group', $groups, 
                    null, 
                    ['class' => 'form-control', 'placeholder' => 'Pick a option...', 'required' => true, 'id' => 'groups']) 
                !!}
              @error('group')
                  <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>

          <div class="form-group" id="provider-field" style="display: none;">
            
          </div>

          <div class="form-group">
            {!! Form::label('location', 'Location', ['class' => 'required']) !!}
            {!! Form::select('location', $locations, 
                    null, 
                    ['class' => 'form-control', 'placeholder' => 'Pick a option...', 'required' => true, 'id' => 'location']) 
                !!}
              @error('location')
                  <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>

          <div class="form-group">
            {!! Form::label('year', 'Year', ['class' => 'required']) !!}
            {!! Form::text('year', date('Y'), array_merge(['class' => 'form-control'], ['required' => true] ) ) !!}
              @error('year')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>

        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
   
  </div>

  <div class="row">
    <div class="col-12">

      {!! Form::submit(trans('app.buttons.save'), ['class' => 'btn btn-success']) !!}
      {!! link_to_route('sra.index',  trans('app.buttons.cancel'), $parameters = [],  ['class' => 'btn btn-secondary']) !!} 
    </div>
  </div>
  {!! Form::close() !!}
  @if(!empty($sra))
  
  <div class="row">
  </div>
 <div class="row">
         <div class="col-12">
            <div class="card">
             
               <!-- /.card-header -->
               <div class="card-body">
                  <table id="example1" class="table table-bordered table-striped">
                     <thead>
                        <tr>
                           <th>S.No</th>
                           <th>Group</th>
                           <th>Providers</th>
                           <th>Location</th>
                           <th>Year</th>
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody>
                     @php $counter = 0; @endphp
                     @foreach($sra as $value)
                        <tr>
                           <td>{{ ++$counter }}</td>
                           <td>{{ $value->hasGroup['name'] }}</td>
                           <td>
                              @php $pr = [] @endphp
                               @foreach($value->hasGroup['hasProviders'] as $innerValue)
                                @php $pr[] = $innerValue->name @endphp
                               @endforeach

                               {{ implode(', ', $pr)}}
                           </td>
                           <td>{{ $value->hasLocation['location'] }}</td>
                           <td>{{ $value->year }}</td>
                           <td>
                             <a title="Create new sra from this previous sra?" href="{{ route('sra-map.show', $value->id) }}">Create Copy</a>
                           </td>
                        </tr>
                     @endforeach
                     </tbody>
                     <tfoot>
                        <tr>
                           <th>S.No</th>
                           <th>Group</th>
                           <th>Providers</th>
                           <th>Location</th>
                           <th>Year</th>
                           <th>Action</th>
                        </tr>
                     </tfoot>
                  </table>
               </div>
               <!-- /.card-body -->
            </div>
            <!-- /.card -->
         </div>
         <!-- /.col -->
      </div>
      <!-- /.row -->


@endif
</section>
<!-- /.content -->

<div class="modal fade" id="modal-lg-sra" data-backdrop="static" data-keyboard="false">
   <div class="modal-dialog modal-lg">
      <div class="modal-content">
         <div class="modal-header bg-teal">
            <h4 class="modal-title"></h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
         </div>
         {!! Form::open(['id' =>'generate-field']) !!}
         <div class="modal-body">
         </div>
         <div class="modal-footer justify-content-between">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            {!! Form::submit(trans('app.buttons.save'), ['class' => 'btn btn-success', 'id' =>'save-field']) !!}
         </div>
      </div>
      <!-- /.modal-content -->
      {!! Form::close() !!}
   </div>
   <!-- /.modal-dialog -->
</div>
<!-- /.modal -->



@endsection

resources/views/admin/module/sra/_edit.blade.php
@extends('admin.layouts.master')

@section('title', 'Edit SRA')

@section('content')

<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">@yield('title')</h3>

        </div>
        
        {!! Form::open(['route' => ['sra.update', $sra->id], 'files' => true, 'method'=>'PUT']) !!}
        
        <div class="card-body">
         
         <div class="form-group"> 

           {!! Form::label('previous sra', 'Generate from previous year', ['class' => 'required']) !!} 

           {!! Form::radio('previous_year', '1', !empty($sra->is_previous != NULL) ? true : false, ['disabled' => true]) !!}
           {!! Form::label('yes', 'Yes') !!}

           {!! Form::radio('previous_year', '0', !empty($sra->is_previous == NULL) ? true : false, ['disabled' => true]) !!}
           {!! Form::label('no', 'No') !!}

         </div>

         <div class="form-group">
              {!! Form::label('group', 'Group', ['class' => 'required']) !!}
              (<small>
                <a target="_blank" href="{{ route('group.create') }}" class="">
                  <i class="fa fa-plus"></i>Add Group
                </a>
              </small>)
              {!! Form::select('group', $groups, 
                    $sra->group, 
                    ['class' => 'form-control', 'placeholder' => 'Pick a option...', 'required' => true, 'id' => 'groups']) 
                !!}
              @error('group')
                  <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>

          <div class="form-group" id="provider-field" >

            {!! Form::label('provider', 'Provider', ['class' => 'required']) !!} 
               (<small>
                   <a target="_blank" href="{{ route('provider.create') }}" class="">
                           <i class="fa fa-plus"></i>Add Provider
                   </a>
              </small>)
              {!! Form::select('provider[]', $providers, 
                                  explode(',', $sra->provider), 
                                  ['class' => 'form-control select2','placeholder' => 'Pick a option...', 'multiple' => true]) 
                              !!}
              @error('provider')
                <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                </span>
              @enderror
            
          </div>

          <div class="form-group">
            {!! Form::label('location', 'Location', ['class' => 'required']) !!}
            {!! Form::select('location', $locations, 
                    $sra->location, 
                    ['class' => 'form-control', 'placeholder' => 'Pick a option...', 'required' => true, 'id' => 'location']) 
                !!}
              @error('location')
                  <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>

          <div class="form-group">
            {!! Form::label('year', 'Year', ['class' => 'required']) !!}
            {!! Form::text('year', !empty($sra->year) ? $sra->year : date('Y'), array_merge(['class' => 'form-control'], ['required' => true] ) ) !!}
              @error('year')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>

        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
   
  </div>

  <div class="row">
    <div class="col-12">

      {!! Form::submit(trans('app.buttons.save'), ['class' => 'btn btn-success']) !!}
      {!! link_to_route('sra.index',  trans('app.buttons.cancel'), $parameters = [],  ['class' => 'btn btn-secondary']) !!} 
    </div>
  </div>
  {!! Form::close() !!}

</section>
<!-- /.content -->


@endsection

resources/views/admin/module/sra/_index.blade.php
@extends('admin.layouts.master')

@section('title', 'Manage SRA')

@section('content')

<section class="content">
   <div class="container-fluid">
      <div class="row">
         <div class="col-12">
            <div class="card">
               <div class="card-header">
                  <a href="{{ route('sra.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Create SRA</a>
               </div>
               <!-- /.card-header -->
               <div class="card-body">
                  <table id="example1" class="table table-bordered table-striped">
                     <thead>
                        <tr>
                           <th>S.No</th>
                           <th>Group</th>
                           <th>Providers</th>
                           <th>Previos Year Sra ?</th>
                           <th>Location</th>
                           <th>Year</th>
                           <th>Created At</th>
                           <th>Status</th>
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody>
                     @php $counter = 0; @endphp
                     @foreach($sra as $value)
                        <tr>
                           <td>{{ ++$counter }}</td>
                           <td>{{ $value->hasGroup['name'] }}</td>
                           <td>
                              @php $pr = [] @endphp
                               @foreach($value->hasGroup['hasProviders'] as $innerValue)
                                @php $pr[] = $innerValue->name @endphp
                               @endforeach

                               {{ implode(', ', $pr)}}
                           </td>
                           <td>{{ ($value->is_previous == 1) ? 'YES' : 'NO' }}</td>
                           <td>{{ $value->hasLocation['location'] }}</td>
                           <td>{{ $value->year }}</td>
                           <td>{{ \Carbon\Carbon::parse($value->created_at)->format('d/m/Y') }}</td>
                           <td>{{ !empty($value->status == 1) ? 'Completed' : 'Pending' }}</td>
                           <td>
                              {!! link_to_route('sra.edit',  trans('app.actions.edit'), $parameters = [$value->id ],  ['class' => 'btn btn-secondary']) !!}

                              {!! link_to_route('sra.show',  trans('app.actions.proceed'), $parameters = [$value->id],  ['class' => 'btn btn-success']) !!} 

                               
                           </td>
                        </tr>
                     @endforeach
                     </tbody>
                     <tfoot>
                        <tr>
                           <th>S.No</th>
                           <th>Group</th>
                           <th>Providers</th>
                           <th>Previos Sra ?</th>
                           <th>Location</th>
                           <th>Year</th>
                           <th>Created At</th>
                           <th>Status</th>
                           <th>Action</th>
                        </tr>
                     </tfoot>
                  </table>
               </div>
               <!-- /.card-body -->
            </div>
            <!-- /.card -->
         </div>
         <!-- /.col -->
      </div>
      <!-- /.row -->
   </div>
   <!-- /.container-fluid -->
</section>


@endsection