routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes :::: Admin
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => ['auth', 'verified']], function() {
 
	Route::get('/admin/dashboard', [App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('admin.dashboard');

	Route::resource('admin/sections', App\Http\Controllers\Admin\SectionsController::class, ['except' => ['']]);

	Route::resource('admin/section-ordering', App\Http\Controllers\Admin\SectionSortingController::class, ['except' => []]);

	Route::resource('admin/manage-form', App\Http\Controllers\Admin\FormBuilderController::class, ['except' => ['create']]);

	Route::resource('admin/users', App\Http\Controllers\Admin\UsersController::class, ['except' => ['']]);
   Route::resource('admin/change-password', App\Http\Controllers\Admin\ChangePasswordController::class, ['except' => ['show', 'edit', 'destroy','update', 'create']]);
   
   Route::resource('admin/profile-setting', App\Http\Controllers\Admin\ProfileSettingController::class, ['except' => ['show', 'edit', 'destroy','update', 'create']]);

   Route::resource('admin/developer-console', App\Http\Controllers\Admin\ArtisanConsoleController::class, ['except' => []]);

   Route::resource('admin/section-type', App\Http\Controllers\Admin\SraTypeController::class, ['except' => ['show', 'delete']]);

   Route::resource('admin/sra', App\Http\Controllers\Admin\SraController::class, ['except' => []]);
   
   Route::post('admin/change-field-status', [App\Http\Controllers\Admin\AjaxHandlerController::class, 'index']);

   Route::post('admin/change-section-status', [App\Http\Controllers\Admin\AjaxHandlerController::class, 'changeSecionStatus']);

    Route::post('admin/change-sra-status', [App\Http\Controllers\Admin\AjaxHandlerController::class, 'changeSraStatus']);
   
   Route::post('admin/create-form-field', [App\Http\Controllers\Admin\AjaxHandlerController::class, 'createFormField']);

   Route::post('admin/show-form-field', [App\Http\Controllers\Admin\AjaxHandlerController::class, 'showFormField']);

   Route::resource('admin/form-fields', App\Http\Controllers\Admin\FormFieldOrderingController::class, ['except' => ['create', 'index', 'edit', 'update', 'show', 'destroy']]);

   Route::resource('admin/media', App\Http\Controllers\Admin\MediaController::class, ['except' => ['edit', 'update']]);

   Route::resource('admin/location', App\Http\Controllers\Admin\LocationController::class, ['except' => []]);

   Route::resource('admin/group', App\Http\Controllers\Admin\GroupController::class, ['except' => []]);

   Route::resource('admin/provider', App\Http\Controllers\Admin\ProviderController::class, ['except' => []]);

   Route::resource('admin/sra-map', App\Http\Controllers\Admin\SraMappingController::class, ['except' => []]);

   Route::resource('admin/sra-document', App\Http\Controllers\Admin\SraDocumentController::class, ['except' => []]);

   Route::resource('admin/sra-report', App\Http\Controllers\Admin\SraReportController::class, ['except' => []]);


   Route::get('admin/completed-sra', [App\Http\Controllers\Admin\CommonController::class, 'index'])->name('completed.sra');


});


routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

include('admin.php');

app/Models/Section.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Section extends Model
{
    use HasFactory;

     /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'description',
        'ordering',
        'status',
        'sra'
    ];

    
     /**
     * The attributes that are used to select.
     *
     * @var array
     */
    public static function sectionAttributes() {
        
        $selectAttr = self::where('status', 1)->get()->pluck('name', 'id');

        return $selectAttr;
    }


     /**
     * The attributes that are used to select.
     *
     * @var array
     */

    public static function sectionAttributesBySra($sra) {
           
        $selectAttr = self::where(['status'=> 1, 'sra' => $sra])->get()->pluck('name', 'id');

        return $selectAttr;
    }

     /**
     * associations belongs to form fields
     *
     * @var array
     */
    
    public function formFields() {

        return $this->hasMany('App\Models\FormField', 'section_id', 'id');
    }

    /**
     * return the associated sra data of the user.
     *
     * @var array
     */
    public function hasSra() {

        return $this->belongsTo('App\Models\SraType', 'sra', 'id');
    }

   
    
   
}

app/Http/Controllers/Admin/SectionsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Section;
use App\Models\FormField;
use App\Models\SectionOrder;
use App\Models\SraType;
use App\Http\Requests\Section\SectionStoreRequest;
use App\Http\Requests\Section\SectionUpdateRequest;
use DB;

class SectionsController extends Controller
{   
    private $model_name;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware(['auth']);
        $this->model_name = trans('app.model.section');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {   
        $sections = Section::with(['hasSra'])->orderBy('id', 'DESC')->get();
        
        return view('admin.module.section._index', compact('sections') );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   
        $SraTypeAttr = SraType::sraTypeAttributes();

        return view('admin.module.section._create', compact('SraTypeAttr'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SectionStoreRequest $request)
    {   

        $orderDB = DB::table('sections')->max('ordering');
        
        $order = !empty($orderDB) ? $orderDB + 1 : 1;

        $section = Section::create( array_merge($request->all(), ['ordering' => $order ] ));

        if( ! $section)
            return back()->with('error', trans('messages.failed'));

        return back()->with('success', trans('messages.created', ['model' => $this->model_name]));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Section $section)
    {   
        $form_fields = FormField::where(['section_id' => $section->id])->orderBy('ordering', 'ASC')->get();
        
        return view('admin.module.section._view', compact('section', 'form_fields'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Section $section)
    {  
        $SraTypeAttr = SraType::sraTypeAttributes();

        return view('admin.module.section._edit', compact('section', 'SraTypeAttr'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(SectionUpdateRequest $request, Section $section)
    {   

        if( $section->update($request->all()) )
            return back()->with('success', trans('messages.updated', ['model' => $this->model_name]));

        return back()->with('error', trans('messages.failed'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/module/section/_create.blade.php
@extends('admin.layouts.master')

@section('title', 'Add section')

@section('content')

<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-md-10">
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">@yield('title')</h3>

        </div>

        {!! Form::open(['route' => 'sections.store', 'files' => true]) !!}
        <div class="card-body">

         <div class="form-group">
              {!! Form::label('type', 'Sra type', ['class' => 'required']) !!}
              {!! Form::select('sra', $SraTypeAttr, 
                    null, 
                    ['class' => 'form-control','placeholder' => 'Pick a option...']) 
                !!}
              @error('status')
                  <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>

          <div class="form-group">
            {!! Form::label('name', 'Name', ['class' => 'required']) !!}
            {!! Form::text('name', old('name'), array_merge(['class' => 'form-control'], ['required' => true] ) ) !!}
              @error('name')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>

          <div class="form-group">
            {!! Form::label('description', 'Description', ['class' => 'awesome']) !!} 
            {!! Form::textarea('description', old('description'), array_merge(['class' => 'form-control'], ['required' => true], ['rows' => 4] ) ) !!}
             @error('description')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>

          <div class="form-group">
              {!! Form::label('status', 'Status', ['class' => 'required']) !!}
              {!! Form::select('status', [
                    '1' => trans('app.dropdown.active'), 
                     '2' => trans('app.dropdown.inactive')
                    ], 
                    null, 
                    ['class' => 'form-control','placeholder' => 'Pick a option...']) 
                !!}
              @error('status')
                  <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>

           <div class="form-group">
            {!! Form::label('class_attribute', 'Class attribute', ['class' => 'required']) !!}
            {!! Form::text('class_attribute', old('class_attribute'), array_merge(['class' => 'form-control'] ) ) !!}
              @error('class_attribute')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>

          <div class="form-group">
            {!! Form::label('id_attribute', 'Id attribute', ['class' => 'required']) !!}
            {!! Form::text('id_attribute', old('id_attribute'), array_merge(['class' => 'form-control'] ) ) !!}
              @error('id_attribute')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>
        
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
   
  </div>

  <div class="row">
    <div class="col-12">
      {!! Form::submit(trans('app.buttons.save'), ['class' => 'btn btn-success']) !!}
      {!! link_to_route('sections.index',  trans('app.buttons.cancel'), $parameters = [],  ['class' => 'btn btn-secondary']) !!} 
    </div>
  </div>
  {!! Form::close() !!}
</section>
<!-- /.content -->

@endsection

resources/views/admin/module/section/_edit.blade.php
@extends('admin.layouts.master')

@section('title', 'Edit section')

@section('content')

<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-md-10">
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">@yield('title')</h3>
       
        </div>

        {!! Form::open(['route' => ['sections.update', $section->id], 'files' => true, 'method'=>'PUT']) !!}

        <div class="card-body">

          <div class="form-group">
              {!! Form::label('type', 'Sra type', ['class' => 'required']) !!}
              {!! Form::select('sra', $SraTypeAttr, 
                    $section->sra, 
                    ['class' => 'form-control','placeholder' => 'Pick a option...']) 
                !!}
              @error('sra')
                  <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>

          <div class="form-group">
            {!! Form::label('name', 'Name', ['class' => 'required']) !!}
            {!! Form::text('name', old('name', $section->name), array_merge(['class' => 'form-control'], ['required' => true] ) ) !!}
              @error('name')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>

          <div class="form-group">
            {!! Form::label('description', 'Description', ['class' => 'awesome']) !!} 
            {!! Form::textarea('description', old('description', $section->description), array_merge(['class' => 'form-control'], ['required' => true], ['rows' => 4] ) ) !!}
             @error('description')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>

          <div class="form-group">
              {!! Form::label('status', 'Status', ['class' => 'required']) !!}
              {!! Form::select('status', [
                     '1' => trans('app.dropdown.active'), 
                     '2' => trans('app.dropdown.inactive')
                    ], 
                    $section->status, 
                    ['class' => 'form-control','placeholder' => 'Pick a option...']) 
                !!}
              @error('status')
                  <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>

          <div class="form-group">
            {!! Form::label('class_attribute', 'Class attribute', ['class' => 'required']) !!}
            {!! Form::text('class_attribute', $section->class_attribute, array_merge(['class' => 'form-control'] ) ) !!}
              @error('class_attribute')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>

          <div class="form-group">
            {!! Form::label('id_attribute', 'Id attribute', ['class' => 'required']) !!}
            {!! Form::text('id_attribute', $section->class_attribute, array_merge(['class' => 'form-control'] ) ) !!}
              @error('id_attribute')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>
        
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
   
  </div>

  <div class="row">
    <div class="col-12">
      {!! Form::submit('Submit', ['class' => 'btn btn-success']) !!}
      {!! link_to_route('sections.index',  'Cancel', $parameters = [],  ['class' => 'btn btn-secondary']) !!} 
    </div>
  </div>
  {!! Form::close() !!}
</section>
<!-- /.content -->
@endsection

resources/views/admin/module/section/_index.blade.php
@extends('admin.layouts.master')

@section('title', 'Sections')

@section('content')

<section class="content">
   <div class="container-fluid">
      <div class="row">
         <div class="col-12">
            <div class="card">
               <div class="card-header">
                  <a href="{{ route('sections.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Add Section</a>
               </div>
               <!-- /.card-header -->
               <div class="card-body">
                  <table id="example1" class="table table-bordered table-striped">
                     <thead>
                        <tr>
                           <th>S.No</th>
                           <th>Name</th>
                           <th>Type</th>
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody>
                     @php $counter = 0; @endphp
                     @foreach($sections as $value)
                        <tr>
                           <td>#{{ ++$counter }}</td>
                           <td>{{ $value->name }}</td>
                        
                           <td>{{ $value->hasSra['name'] }} </td>
                           <td>
                           	{!! link_to_route('sections.edit',  trans('app.actions.edit'), $parameters = [$value->id ],  ['class' => 'btn btn-secondary']) !!}

                              {!! link_to_route('sections.show',  trans('app.actions.view'), $parameters = [$value->id],  ['class' => 'btn btn-success']) !!} 
                              
                  
                           </td>
                        </tr>
                     @endforeach
                     </tbody>
                     <tfoot>
                        <tr>
                           <th>S.No</th>
                           <th>Name</th>
                           <th>Description</th>
                           <th>Action</th>
                        </tr>
                     </tfoot>
                  </table>
               </div>
               <!-- /.card-body -->
            </div>
            <!-- /.card -->
         </div>
         <!-- /.col -->
      </div>
      <!-- /.row -->
   </div>
   <!-- /.container-fluid -->
</section>


@endsection

resources/views/admin/module/section/_view.blade.php
@extends('admin.layouts.master')

@section('title', 'View Section')

@section('content')

<style type="text/css">
   .slist {
     list-style: none;
     padding: 0;
     margin: 0;
   }
   .slist li {
     margin: 5px;
     padding: 10px;
     border: 1px solid #333;
     background: #eaeaea;
   }
   /* (B) DRAG-AND-DROP HINT */
   .slist li.hint { background: #fea; }
   .slist li.active { background: #ffd4d4; }
</style>
<section class="content">
   <div class="container-fluid">

      <div class="row">
         <div class="card-body">
            
             <div class="callout callout-info">
                  <h5>Drag and Drop</h5>
                  <p>{{ trans('messages.ordering.form_fields') }}</p>
                   <p>{{ trans('messages.ordering.active_inactive') }}</p>
             </div>
       
            <div id="accordion">
               <div class="card card-success">
                  <div class="card-header">
                     <h4 class="card-title w-100">
                        <a class="d-block w-100" data-toggle="collapse" href="#collapseOne">
                        {{ $section->name }}
                        </a>
                     </h4>
                  </div>
                  <div id="collapseOne" class="collapse show" data-parent="#accordion">
                     <div class="card-body">
                        <div class="tab-content p-0">
                           <!-- Morris chart - Sales -->
                           <ul id="sortFormField">
                              @foreach($form_fields as $data)

                                <!------------ TEXT ------------->
                                @if($data->field_type =='text')

                                <li data-id="{{ $data->id }}" data-order="{{ $data->ordering }}">
                                   @include('admin.module.form-builder.fields._input', $data)
                                </li>
                                
                                <!------------ EMAIL ------------->

                                @elseif($data->field_type =='email')

                                <li data-id="{{ $data->id }}" data-order="{{ $data->ordering }}">
                                   @include('admin.module.form-builder.fields._input', $data)
                                </li>

                                <!------------ URL ------------->

                                @elseif($data->field_type == 'url')

                                <li data-id="{{ $data->id }}" data-order="{{ $data->ordering }}">
                                  @include('admin.module.form-builder.fields._url', $data) 
                                </li>

                                <!------------ NUMBER ------------->

                                @elseif($data->field_type == 'number')

                                <li data-id="{{ $data->id }}" data-order="{{ $data->ordering }}"> 
                                   @include('admin.module.form-builder.fields._number', $data) 
                                </li>

                                <!------------ TEXTAREA ------------->

                                @elseif($data->field_type == 'textarea')

                                <li data-id="{{ $data->id }}" data-order="{{ $data->ordering }}"> 
                                    @include('admin.module.form-builder.fields._textarea', $data) 
                                </li>

                                <!------------ RADIO BUTTONS ------------->

                                @elseif($data->field_type == 'radio-buttons')

                                <li data-id="{{ $data->id }}" data-order="{{ $data->ordering }}">
                                   @include('admin.module.form-builder.fields._radio', $data) 
                                </li>

                                <!------------ CHECKBOXES ------------->

                                @elseif($data->field_type == 'checkboxes')

                                <li data-id="{{ $data->id }}" data-order="{{ $data->ordering }}"> 
                                    @include('admin.module.form-builder.fields._checkbox', $data)
                                 </li>

                                 <!------------ DROP DOWN ------------->

                                @elseif($data->field_type == 'drop-down')

                                <li data-id="{{ $data->id }}" data-order="{{ $data->ordering }}">    
                                    @include('admin.module.form-builder.fields._select', $data)
                                </li>

                                <!------------ File ------------->

                                @elseif($data->field_type == 'file')

                                <li data-id="{{ $data->id }}" data-order="{{ $data->ordering }}">    
                                    @include('admin.module.form-builder.fields._file', $data)
                                </li>

                                <!------------ DATE ------------->

                                @elseif($data->field_type == 'date')

                                <li data-id="{{ $data->id }}" data-order="{{ $data->ordering }}">    
                                    @include('admin.module.form-builder.fields._date', $data)
                                </li>

                                <!------------ TEL ------------->

                                @elseif($data->field_type == 'tel')

                                <li data-id="{{ $data->id }}" data-order="{{ $data->ordering }}">    
                                    @include('admin.module.form-builder.fields._tel', $data)
                                </li>

                                @else

                                @endif

                              @endforeach
                           </ul>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <!-- /.col -->
      </div>
      <!-- /.row -->
   </div>
   <!-- /.container-fluid -->
</section>
@endsection