routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes :::: Admin
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => ['auth', 'verified']], function() {
 
	Route::get('/admin/dashboard', [App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('admin.dashboard');

	Route::resource('admin/sections', App\Http\Controllers\Admin\SectionsController::class, ['except' => ['']]);

	Route::resource('admin/section-ordering', App\Http\Controllers\Admin\SectionSortingController::class, ['except' => []]);

	Route::resource('admin/manage-form', App\Http\Controllers\Admin\FormBuilderController::class, ['except' => ['create']]);

	Route::resource('admin/users', App\Http\Controllers\Admin\UsersController::class, ['except' => ['']]);
   Route::resource('admin/change-password', App\Http\Controllers\Admin\ChangePasswordController::class, ['except' => ['show', 'edit', 'destroy','update', 'create']]);
   
   Route::resource('admin/profile-setting', App\Http\Controllers\Admin\ProfileSettingController::class, ['except' => ['show', 'edit', 'destroy','update', 'create']]);

   Route::resource('admin/developer-console', App\Http\Controllers\Admin\ArtisanConsoleController::class, ['except' => []]);

   Route::resource('admin/section-type', App\Http\Controllers\Admin\SraTypeController::class, ['except' => ['show', 'delete']]);

   Route::resource('admin/sra', App\Http\Controllers\Admin\SraController::class, ['except' => []]);
   
   Route::post('admin/change-field-status', [App\Http\Controllers\Admin\AjaxHandlerController::class, 'index']);

   Route::post('admin/change-section-status', [App\Http\Controllers\Admin\AjaxHandlerController::class, 'changeSecionStatus']);

    Route::post('admin/change-sra-status', [App\Http\Controllers\Admin\AjaxHandlerController::class, 'changeSraStatus']);
   
   Route::post('admin/create-form-field', [App\Http\Controllers\Admin\AjaxHandlerController::class, 'createFormField']);

   Route::post('admin/show-form-field', [App\Http\Controllers\Admin\AjaxHandlerController::class, 'showFormField']);

   Route::resource('admin/form-fields', App\Http\Controllers\Admin\FormFieldOrderingController::class, ['except' => ['create', 'index', 'edit', 'update', 'show', 'destroy']]);

   Route::resource('admin/media', App\Http\Controllers\Admin\MediaController::class, ['except' => ['edit', 'update']]);

   Route::resource('admin/location', App\Http\Controllers\Admin\LocationController::class, ['except' => []]);

   Route::resource('admin/group', App\Http\Controllers\Admin\GroupController::class, ['except' => []]);

   Route::resource('admin/provider', App\Http\Controllers\Admin\ProviderController::class, ['except' => []]);

   Route::resource('admin/sra-map', App\Http\Controllers\Admin\SraMappingController::class, ['except' => []]);

   Route::resource('admin/sra-document', App\Http\Controllers\Admin\SraDocumentController::class, ['except' => []]);

   Route::resource('admin/sra-report', App\Http\Controllers\Admin\SraReportController::class, ['except' => []]);


   Route::get('admin/completed-sra', [App\Http\Controllers\Admin\CommonController::class, 'index'])->name('completed.sra');


});


routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

include('admin.php');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'sections',
        'sra',
        'role'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * return the associated role data of the user.
     *
     * @var array
     */
    public function hasRole() {

        return $this->belongsTo('App\Models\Role', 'role', 'id');
    }

    /**
     * return the associated sra data of the user.
     *
     * @var array
     */
    public function hasSra() {

        return $this->belongsTo('App\Models\SraType', 'sra', 'id');
    }

}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Section;
use App\Models\Role;
use App\Models\SraType;
use App\Http\Requests\User\UserStoreRequest;
use App\Http\Requests\User\UserUpdateRequest;
use Illuminate\Support\Facades\Hash;
use App\Http\Traits\Common;

class UsersController extends Controller
{   

    private $model_name;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->model_name = trans('app.model.user');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::with(['hasRole', 'hasSra'])->where('id', '!=', 1)->orderBy('id', 'DESC')->get();
        
        return view('admin.module.user._index', compact('users') );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {   
        if($request->ajax()) {
               
            $selectAttr   = Section::sectionAttributesBySra($request->sra);

            $return[] = view('admin.module.user._ajax-section')->with(['selectAttr' => $selectAttr])->render();

            return response()->json(['message' => $return ]);
        }

        
        $selectRole     = Role::roleAttributes();
        $selectSraType  = SraType::sraTypeAttributes();
    
        return view('admin.module.user._create', compact('selectRole', 'selectSraType'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserStoreRequest $request)
    {
        $userArr = [ 
                'name'     => $request->name, 
                'email'    => $request->email,
                'password' => Hash::make($request->password), 
                'sections' => implode(',', $request->section),
                'role'     => $request->role,
                'sra'      => $request->sra
        ];

        $user = User::create($userArr);
        if( ! $user)
            return back()->with('error', trans('messages.failed'));

        return back()->with('success', trans('messages.created', ['model' => $this->model_name]));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {   

        $sections = Section::with(['formFields' => function ($q){
                        $q->orderBy('ordering', 'ASC');
                    }])->whereIn('id', explode(',', $user->sections))->orderBy('ordering', 'ASC')->get();
       
        return view('admin.module.user._show', compact('user', 'sections'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {   
        $selectAttr    = Section::sectionAttributesBySra($user->sra);
        $selectRole    = Role::roleAttributes();
        $selectSraType = SraType::sraTypeAttributes();
        
        return view('admin.module.user._edit', compact('user', 'selectAttr', 'selectRole', 'selectSraType'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserUpdateRequest $request, User $user)
    {
          $userArr = [ 
                'name'     => $request->name, 
                'email'    => $request->email,
                'sections' => implode(',', $request->section),
                'role'     => $request->role,
                'sra'      => $request->sra
        ];
        $user = User::where('id', $user->id)->update($userArr);
        if( ! $user)
            return back()->with('error', trans('messages.failed'));

        return back()->with('success', trans('messages.updated', ['model' => $this->model_name]));

        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/module/user/_ajax-section.blade.php
 {!! Form::label('section', 'Sections', ['class' => 'required']) !!}
              <small class="text-primary">(Assign sections to user)</small>
              {!! Form::select('section[]', $selectAttr, 
                    null, 
                    ['class' => 'select2 form-control','data-placeholder' => 'Pick an option...', 'required' => true, 'multiple' => 'multiple']) 
                !!}
                @error('section')
                      <span class="invalid-feedback" role="alert">
                          <strong>{{ $message }}</strong>
                      </span>
                  @enderror  

resources/views/admin/module/user/_create.blade.php
@extends('admin.layouts.master')

@section('title', 'Add User')

@section('content')

<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-md-10">
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">@yield('title')</h3>

        </div>
        
        {!! Form::open(['route' => 'users.store', 'files' => true]) !!}
        <div class="card-body">

          <div class="form-group">
            {!! Form::label('name', 'Name', ['class' => 'required']) !!}
            {!! Form::text('name', old('name'), array_merge(['class' => 'form-control'], ['required' => true] ) ) !!}
              @error('name')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>

          <div class="form-group">
            {!! Form::label('email', 'Email', ['class' => 'required']) !!}
            {!! Form::text('email', old('email'), array_merge(['class' => 'form-control'], ['required' => true] ) ) !!}
              @error('email')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>

          <div class="form-group">
              {!! Form::label('sra', 'SRA', ['class' => 'required']) !!}
              {!! Form::select('sra', $selectSraType, 
                    null, 
                    ['class' => 'form-control','placeholder' => 'Pick an option...', 'required' => true, 'id'=>'get-sections']) 
                !!}
                @error('sra')
                      <span class="invalid-feedback" role="alert">
                          <strong>{{ $message }}</strong>
                      </span>
                  @enderror  
          </div>

           <div class="form-group" id="user-sections" style="display: none;">
             
          </div>


          <div class="form-group">
              {!! Form::label('user role', 'Role', ['class' => 'required']) !!}
              {!! Form::select('role', $selectRole, 
                    null, 
                    ['class' => 'form-control','placeholder' => 'Pick an option...', 'required' => true]) 
                !!}
                @error('role')
                      <span class="invalid-feedback" role="alert">
                          <strong>{{ $message }}</strong>
                      </span>
                  @enderror  
          </div>


          <div class="form-group">
            {!! Form::label('password', 'Password', ['class' => 'required']) !!}
            {!! Form::text('password', null, array_merge(['class' => 'form-control'], ['required' => true] ) ) !!}
              @error('password')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>

          <div class="form-group">
            {!! Form::label('password-confirm', 'Confirm Password', ['class' => 'required']) !!}
            {!! Form::text('password_confirmation', null, array_merge(['class' => 'form-control'], ['required' => true] ) ) !!}
          </div>
        
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
   
  </div>

  <div class="row">
    <div class="col-12">
      {!! Form::submit(trans('app.buttons.save'), ['class' => 'btn btn-success']) !!}
      {!! link_to_route('sections.index',  trans('app.buttons.cancel'), $parameters = [],  ['class' => 'btn btn-secondary']) !!} 
    </div>
  </div>
  {!! Form::close() !!}
</section>
<!-- /.content -->

@endsection

resources/views/admin/module/user/_edit.blade.php
@extends('admin.layouts.master')

@section('title', 'Edit User')

@section('content')

<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-md-10">
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">@yield('title')</h3>

        </div>
      
        {!! Form::open(['route' => ['users.update', $user->id], 'files' => true, 'method'=>'PUT']) !!}

         <div class="card-body">

          <div class="form-group">
            {!! Form::label('name', 'Name', ['class' => 'required']) !!}
            {!! Form::text('name', old('name', $user->name), array_merge(['class' => 'form-control'], ['required' => true] ) ) !!}
              @error('name')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>

          <div class="form-group">
            {!! Form::label('email', 'Email', ['class' => 'required']) !!}
            {!! Form::text('email', old('email', $user->email), array_merge(['class' => 'form-control'], ['required' => true] ) ) !!}
              @error('email')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>

          <div class="form-group">
              {!! Form::label('sra', 'SRA', ['class' => 'required']) !!}
              {!! Form::select('sra', $selectSraType, 
                    $user->sra, 
                    ['class' => 'form-control','placeholder' => 'Pick an option...', 'required' => true, 'id' => 'get-sections']) 
                !!}
                @error('sra')
                      <span class="invalid-feedback" role="alert">
                          <strong>{{ $message }}</strong>
                      </span>
                  @enderror  
          </div>

           <div class="form-group" id="user-sections">
              {!! Form::label('section', 'Sections', ['class' => 'required']) !!}
              <small class="text-primary">(Assign sections to user)</small>
              {!! Form::select('section[]', $selectAttr, 
                    explode(',',$user->sections), 
                    ['class' => 'select2 form-control','data-placeholder' => 'Pick an option...', 'required' => true, 'multiple' => 'multiple']) 
                !!}
                @error('section')
                      <span class="invalid-feedback" role="alert">
                          <strong>{{ $message }}</strong>
                      </span>
                  @enderror  
          </div>

          <div class="form-group">
              {!! Form::label('user role', 'Role', ['class' => 'required']) !!}
              {!! Form::select('role', $selectRole, 
                    $user->role, 
                    ['class' => 'form-control','placeholder' => 'Pick an option...', 'required' => true]) 
                !!}
                @error('role')
                      <span class="invalid-feedback" role="alert">
                          <strong>{{ $message }}</strong>
                      </span>
                @enderror  
          </div>
          
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
   
  </div>

  <div class="row">
    <div class="col-12">
      {!! Form::submit('Submit', ['class' => 'btn btn-success']) !!}
      {!! link_to_route('users.index',  'Cancel', $parameters = [],  ['class' => 'btn btn-secondary']) !!} 
    </div>
  </div>
  {!! Form::close() !!}
</section>
<!-- /.content -->
@endsection

resources/views/admin/module/user/_index.blade.php
@extends('admin.layouts.master')

@section('title', 'Users')

@section('content')

<section class="content">
   <div class="container-fluid">
      <div class="row">
         <div class="col-12">
            <div class="card">
               <div class="card-header">
                  <a href="{{ route('users.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Add User</a>
               </div>
               <!-- /.card-header -->
               <div class="card-body">
                  <table id="example1" class="table table-bordered table-striped">
                     <thead>
                        <tr>
                           <th>S.No</th>
                           <th>Name</th>
                           <th>Email</th>
                           <th>Role</th>
                           <th>SRA</th>
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody>
                     @php $counter = 0; @endphp
                     @foreach($users as $value)
                        <tr>
                           <td>#{{ ++$counter }}</td>
                           <td>{{ $value->name }}</td>
                           <td>{{ $value->email }}</td>
                           <td>{{ $value->hasRole['name'] }}</td>
                           <td>{{ $value->hasSra['name'] }}</td>
                           <td>
                           	{!! link_to_route('users.edit',  trans('app.actions.edit'), $parameters = [$value->id],  ['class' => 'btn btn-secondary']) !!} 
                              {!! link_to_route('users.show',  trans('app.actions.view'), $parameters = [$value->id],  ['class' => 'btn btn-success']) !!} 
                           </td>
                        </tr>
                     @endforeach
                     </tbody>
                     <tfoot>
                        <tr>
                           <th>S.No</th>
                           <th>Name</th>
                           <th>Description</th>
                           <th>Ordering</th>
                           <th>SRA</th>
                           <th>Action</th>
                        </tr>
                     </tfoot>
                  </table>
               </div>
               <!-- /.card-body -->
            </div>
            <!-- /.card -->
         </div>
         <!-- /.col -->
      </div>
      <!-- /.row -->
   </div>
   <!-- /.container-fluid -->
</section>


@endsection

resources/views/admin/module/user/_show.blade.php
@extends('admin.layouts.master')

@section('title', $user->name)

@section('content')

<!-- Main content -->
<section class="content">
   <div class="container-fluid">
      <div class="row">
         <div class="col-md-3">
            <!-- Profile Image -->
            <div class="card card-primary card-outline">
               <div class="card-body box-profile">
                  <div class="text-center">
                     <img class="profile-user-img img-fluid img-circle"
                        src="{{ asset('assets/dist/img/user4-128x128.jpg') }}"
                        alt="User profile picture">
                  </div>
                  <h3 class="profile-username text-center">{{ $user->name }}</h3>
                  <p class="text-muted text-center">{{ $user->hasRole['name'] }} (<b>{{ $user->hasSra['name'] }}</b>)</p>
                  <ul class="list-group list-group-unbordered mb-3">
                    
                     <li class="list-group-item">
                        <b>Sections</b> <a class="float-right">{{ $sections->count() }}</a>
                     </li>
                     <li class="list-group-item">
                        <b>SRA</b> <a class="float-right">543</a>
                     </li>
                     
                  </ul>
                 {!! link_to_route('users.edit',  trans('app.actions.edit'), $parameters = [$user->id],  ['class' => 'btn btn-primary btn-block']) !!} 
               </div>
               <!-- /.card-body -->
            </div>
            <!-- /.card -->
            <!-- About Me Box -->
            <!-- <div class="card card-primary">
               <div class="card-header">
                 <h3 class="card-title">About Me</h3>
               </div>
               
               <div class="card-body">
                 <strong><i class="fas fa-book mr-1"></i> Education</strong>
               
                 <p class="text-muted">
                   B.S. in Computer Science from the University of Tennessee at Knoxville
                 </p>
               
                 <hr>
               
                 <strong><i class="fas fa-map-marker-alt mr-1"></i> Location</strong>
               
                 <p class="text-muted">Malibu, California</p>
               
                 <hr>
               
                 <strong><i class="fas fa-pencil-alt mr-1"></i> Skills</strong>
               
                 <p class="text-muted">
                   <span class="tag tag-danger">UI Design</span>
                   <span class="tag tag-success">Coding</span>
                   <span class="tag tag-info">Javascript</span>
                   <span class="tag tag-warning">PHP</span>
                   <span class="tag tag-primary">Node.js</span>
                 </p>
               
                 <hr>
               
                 <strong><i class="far fa-file-alt mr-1"></i> Notes</strong>
               
                 <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim neque.</p>
               </div>
               
               </div> -->
            <!-- /.card -->
         </div>
         <!-- /.col -->
         <div class="col-md-9">
            <div class="card">
               <div class="card-header p-2">
                  <ul class="nav nav-pills">
                     <li class="nav-item"><a class="nav-link active" href="#activity" data-toggle="tab">Assigned Sections</a></li>
                  </ul>
               </div>
               <!-- /.card-header -->
               <div class="card-body">
                  <div class="tab-content">
                     
                     <div class="active tab-pane" id="activity">
                        <div id="accordion">
                           @foreach($sections as $key => $section)
                           <div class="card card-{{ !empty($section->status == 1) ? 'success' : 'danger' }}">
                              <div class="card-header">
                                 <h4 class="card-title w-100">
                                    <a class="d-block w-100" data-toggle="collapse" href="#collapse{{ readNumber($section->id) }}">
                                    {{ $section->name }}
                                    </a>
                                 </h4>
                              </div>
                              <div id="collapse{{ readNumber($section->id) }}" class="collapse {{ !empty($key == 0) ? 'show' : '' }}" data-parent="#accordion">
                                 <div class="card-body">
                                  @if($section->formFields->count() > 0)
                                  
                                    @foreach($section->formFields as $data)
                                    
                                    <!------------ TEXT -------------->

                                    @if($data->field_type =='text')
                                    
                                       @include('admin.module.form-builder.fields._input', $data)
                                    
                                    <!------------ EMAIL -------------->

                                    @elseif($data->field_type =='email')
                                    
                                       @include('admin.module.form-builder.fields._input', $data)

                                    <!------------ URL -------------->
                                    
                                    @elseif($data->field_type == 'url')
                                      
                                      @include('admin.module.form-builder.fields._url', 
                                    $data)

                                    <!------------ NUMBER -------------->
                                    
                                    @elseif($data->field_type == 'number')
                                    
                                       @include('admin.module.form-builder.fields._number', 
                                    $data) 

                                    <!------------ TEXTAREA -------------->
                                    
                                    @elseif($data->field_type == 'textarea')
                                    
                                       @include('admin.module.form-builder.fields._textarea', $data) 

                                    <!------------ RADIO BUTTONS -------------->
                                    
                                    @elseif($data->field_type == 'radio-buttons')
                                    
                                       @include('admin.module.form-builder.fields._radio', $data) 
                                    
                                    <!------------ CHECKBOXES -------------->

                                    @elseif($data->field_type == 'checkboxes')
                                    
                                       @include('admin.module.form-builder.fields._checkbox', $data)

                                    <!------------ DROP DOWN -------------->
                                    
                                    @elseif($data->field_type == 'drop-down')
                                    
                                       @include('admin.module.form-builder.fields._select', 
                                    $data)

                                    <!------------ FILE -------------->
                                    
                                    @elseif($data->field_type == 'file')
                                    
                                       @include('admin.module.form-builder.fields._file', 
                                    $data)

                                    <!------------ TEL -------------->
                                    
                                    @elseif($data->field_type == 'tel')
                                    
                                       @include('admin.module.form-builder.fields._tel', 
                                    $data)

                                    <!------------ DATE -------------->
                                    
                                    @elseif($data->field_type == 'date')
                                    
                                       @include('admin.module.form-builder.fields._date', 
                                    $data)
                                    
                                    @else
                                    
                                    @endif
                                    
                                    @endforeach
                                 @else
                                    <div class="alert alert-danger alert-dismissible">
                                        
                                        <h5><i class="icon fas fa-ban"></i> Alert!</h5>
                                        {{ trans('messages.alerts.form_field') }}
                                    </div>
                                 @endif

                                 </div>
                              </div>
                           </div>
                           @endforeach
                        </div>
                     </div>
                     <!-- /.tab-pane -->
                  </div>
                  <!-- /.tab-content -->
               </div>
               <!-- /.card-body -->
            </div>
            <!-- /.card -->
         </div>
         <!-- /.col -->
      </div>
      <!-- /.row -->
   </div>
   <!-- /.container-fluid -->
</section>
<!-- /.content -->
@endsection